### ISSUE TITLE
Issue with PC XCOM2 War of the Chosen bnk

### ISSUE THREAD

**Issue by Xehanort88** [bnnm/wwiser#1]
So, when trying to use wwiser with XCOM2, I get this error.
Here is the log:

> wwiser v20201228 (python 3.7.9)
> parser: parsing D:/Steam/steamapps/common/XCOM 2/XCom2-WarOfTheChosen/XComGame/CookedPCConsole/WwiseDefaultBank_SoundMissionSoundtracks.bnk
> parser: done
> names: loading names
> names: done
> generator: start
> generator: ERROR! node 4241966981 in WwiseDefaultBank_SoundMissionSoundtracks.bnk
> generator: PROCESS ERROR! (report)
> 
> Traceback (most recent call last):
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 776, in make_txtp
>     self._process_txtp(txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 1256, in _process_txtp
>     self._process_next(ntid, txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 426, in _process_next
>     bnode = self.builder._get_bnode_by_ref(bank_id, tid, sid_info=self.sid, nbankid_info=nbankid)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 283, in _get_bnode_by_ref
>     bnode = self._get_bnode(node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 340, in _get_bnode
>     bnode.init_node(node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 400, in init_node
>     self._build(node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 1216, in _build
>     self._build_transitions(node, True)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 622, in _build_transitions
>     self.builder.add_transition_segment(ntid)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 207, in add_transition_segment
>     __ = self._get_bnode(node) #force parse/register, but don't use yet
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 340, in _get_bnode
>     bnode.init_node(node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 400, in init_node
>     self._build(node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 1432, in _build
>     self._build_audio_config(node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 560, in _build_audio_config
>     bank_id = nstateid.get_root().get_id()
> AttributeError: 'NoneType' object has no attribute 'get_root'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 776, in make_txtp
>     self._process_txtp(txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 974, in _process_txtp
>     self._process_next(self.ntid, txtp, self.nbankid)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 431, in _process_next
>     bnode.make_txtp(txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 779, in make_txtp
>     raise ValueError("Error processing TXTP for node %i" % (self.sid)) #from e
> ValueError: Error processing TXTP for node 820279197
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 776, in make_txtp
>     self._process_txtp(txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 863, in _process_txtp
>     self._process_next(ntid, txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 431, in _process_next
>     bnode.make_txtp(txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 779, in make_txtp
>     raise ValueError("Error processing TXTP for node %i" % (self.sid)) #from e
> ValueError: Error processing TXTP for node 320739215
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wgenerator.py", line 147, in generate
>     self._write()
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wgenerator.py", line 271, in _write
>     self._write_bank(bank)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wgenerator.py", line 347, in _write_bank
>     self._make_txtp(node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wgenerator.py", line 388, in _make_txtp
>     self._rebuilder.begin_txtp(txtp, node)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 356, in begin_txtp
>     bnode.make_txtp(txtp)
>   File "D:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole\wwiser.pyz\wwiser\wrebuilder.py", line 779, in make_txtp
>     raise ValueError("Error processing TXTP for node %i" % (self.sid)) #from e
> ValueError: Error processing TXTP for node 4241966981
> gui: generator stopped on error

Attached also the bnk file plus the txt file. And two UPK files which share the same name.

[bnktxt.zip](https://github.com/bnnm/wwiser/files/5824198/bnktxt.zip)

**Comment by bnnm** [comment]
Try this: [wwiser.zip](https://github.com/bnnm/wwiser/files/5837755/wwiser.zip)

**Comment by Xehanort88** [comment]
It works much better, thank you so much.
