### ISSUE TITLE
A Total War Saga Troy Unsupported Banks

### ISSUE THREAD

**Issue by kloruklass** [bnnm/wwiser#10]
I'm currently working on another game and I've got the same problem as before.
Can you please take a look and see if there's a way to fix it? The last tweak you did worked perfectly.

Here are the BNK files: [A Total War Saga Troy](https://drive.google.com/file/d/1ME-FRtwSn1S6Saa2POkxJTrv8HbWHT7d/view?usp=sharing)

Thanks.

**Comment by bnnm** [comment]
Should work: [wwiser.zip](https://github.com/bnnm/wwiser/files/7591059/wwiser.zip)

If  you have Try Total War Saga: Thrones of Britannia banks too it, as I suspect they may use another unsupported version.

**Comment by kloruklass** [comment]
It worked, thank you very much!

As for _Thrones of Britannia_, probably you're right.
I will try later today and let you know.

**Comment by kloruklass** [comment]
Yeah, the _Thrones of Britannia_ BNK are unsupported too.
Here: [Thrones of Britannia BNK](https://drive.google.com/file/d/1lF8kvBwfAiwwN8q0UB0FLuq-50aUPx0h/view?usp=sharing)

Thanks in advance for helping.

**Comment by bnnm** [comment]
Done: [wwiser.zip](https://github.com/bnnm/wwiser/files/7597805/wwiser.zip)

**Comment by kloruklass** [comment]
That was great, thanks for your help!
