### ISSUE TITLE
BNK  not recognized

### ISSUE THREAD

**Issue by kloruklass** [bnnm/wwiser#11]
These files have the _.uasset_ extension, but they're clearly BNK. In fact, if you open them with HxD you can see _BKHD_ inside. Plus, I'm quite sure because they're in a folder called Banks. I tried to rename the extension, but anyway they're not recognized as BNK files. It keeps saying: _not a Wwise bank._ I also try with a file cutter but it didn't work.

Here: [Sea of Thieves BNK](https://drive.google.com/file/d/1woOrdQlGhCiDjqQgfHlh9f4Fyim5y5OX/view?usp=sharing)

Thanks in advance.

**Comment by bnnm** [comment]
.uasset is an Unreal Engine generic container, that in this case holds .bnk files, and not a Wwise file.

You need to use a proper UE extractor like [umodel](https://www.gildor.org/en/projects/umodel) or [fmodel](https://github.com/iAmAsval/FModel) to get the bnk inside uassets. Or, manually cut in a hex editor from BKHD to the last 4 bytes (IIRC).

**Comment by kloruklass** [comment]
Alright, thanks for the input.
I've cut the files and seems like it's working for now.

I let you know.
