### ISSUE TITLE
BKHD Cutter

### ISSUE THREAD

**Issue by kloruklass** [bnnm/wwiser#12]
The last time I cut the files did the trick but now looks like it's a little different. The settings you suggested work with some files, but not with other ones. Especially with larger files.

Have a look: [BNK](https://drive.google.com/file/d/1mheAjHzQQK4lLlR1GzJJCsrJVSrNNBz6/view?usp=sharing)

I'm playing with the settings to see if I can get the BNK, but I had no luck so far.

Update
I managed to get the BNK files but they don't load into Wwiser. I keep getting the _parsing error_ issue.
Once I have everything I link them hoping it's possible to find a solution.

Let me know if you need all the banks or just a few ones.

Thanks in advance!!

**Comment by kloruklass** [comment]
So, I left just a few ones. I couldn't include everything otherwise the size would be huge.
I hope it's enough to find a workaround so the other files will parse correctly too.

Here: [BNK](https://drive.google.com/file/d/1splTgDZ3P2uxidP30uZ3XR0oHomPob61/view?usp=sharing)

**Comment by kloruklass** [comment]
The BNKs I sent you were cut by me, but probably something was missing.
I leave you the decompressed files from the original XXX.

Here: [Injustice 2 BNK](https://drive.google.com/file/d/1qcWP9FoLBOfXNZK0e-3wIF3SfbiQFLOs/view?usp=sharing)

I've been trying to figure out a way in these days to make it work, but nothing worked.
I hope you can figure out a way to load them in WWISER.

Let me know, thanks!

**Comment by bnnm** [comment]
I added a bms script to extract .bnk (BKHD)
https://github.com/bnnm/wwiser-utils/blob/master/scripts/bkhd_extractor.bms

Note that this tool only handles properly extracted .bnk. So please, don't bring "extract my game" issues here and ask in xentax/zenhax/elsewhere.

**Comment by kloruklass** [comment]
Hey, thanks a lot for your hard work!

It wasn't my intention to bring up the "extract my game" issue, but I've been trying to extract those BKHD for days, and since they wouldn't load in WWISER (probably due to a bad extraction, as I noticed), asking here was my only solution.

I appreciate your help.

**Comment by bnnm** [comment]
Sure, just let's keep it focused.
