### ISSUE TITLE
Issue with some .txtp in Pokemon Legends Arceus

### ISSUE THREAD

**Issue by Auraylien** [bnnm/wwiser#16]
Hello,
Thanks for making wwiser, this really helps me for ripping music from Switch games!

I'm currently working on the music from Pokemon Legends Arceus and I encountered some problems.

To explain, during some point of the game (battle with wild Pokemon, trainers, ...), some part of the music disappear when we open the menu. Unfortunetly, I don't understand how to get these music variants with wwiser.

To clarify the problem, I uploaded here a ZIP file that contains the battle music against a wild Pokemon in .txtp format (with the .wem if you wants to play it). The name of the file generated by default is `BGM-1733-event (2776459532=3902110436)(bgm_battle=3189526517)(1204638696=-) {s}`. I also put a second file `BGM-1733-event (2776459532=3902110436)(bgm_battle=3189526517)(1204638696=-) {s} {edited}` with the specific variation we can hear ingame (I only comment out some .wem in the .txtp file to obtain the variant). I was wondering how can we get the information of which .wem have to be mutted to get the variation and I figured out that under each .wem comment part in the .txtp file, we can find a line named "CAkEvent", so I concluded that every variant file will have this line to identify the .wem track that have to be mutted. **But**, for an another file also included into the ZIP file and correspond to the trainer battle (`BGM-2315-event (3832295740=4178474359) {d}`), there is no "CAkEvent" line, but a variant for this music also exists (I created a `BGM-2315-event (3832295740=4178474359) {d} {edited}` with one .wem commented out to get the variant). I'm a little bit confused about this and I'm wondering how is it posible to generate the .txtp associated with the variant. I read the doc to understand how the .wem and .txtp formats works, but I'm still lost with some parameters in the .txtp file (`#@layer-v` for example).

Here the link to the ZIP file : https://drive.google.com/file/d/1zb2kYFedaKy8_-u016s8QHW7mKj3Z3sf/view?usp=sharing

So I'm looking for help to learn how to identify and separate variant from a single .txtp file, and also if it's possible, how to get names for the files instead of event ID, I don't really understand the steps to generate the .txt files with wwiser-utils.

Thanks for your help, have a nice day!

**Comment by bnnm** [comment]
Please include the .bnk as, like the tool itself, I can't do much without it.

On a quick glance, probably they are changing volumes manually with a bus to some musictracks/musicsegments (wems). This generally means wwise can't generate automatically variations. Could be using a RTPC 1448701280 to alter volumes too ([see here](https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#crossfade-mark-s))

As for `#@layer-v` it's just basically to simulate how wwise joins audio, that is, layer some .wem while keeping them stereo with volume (-v) as-is.

For names I don't have a better explanation than [this](https://github.com/bnnm/wwiser-utils/blob/master/doc/NAMES.md), but I added a bunch of Pokemon names [here](https://github.com/bnnm/wwiser-utils/blob/master/wwnames/Pokemon%20Legends%20Arceus%20(Switch).txt) (rename to wwnames.txt):

**Comment by Auraylien** [comment]
Thanks for your response.

Sorry, I forgot the most important files! You can find the banks I used for get the .txtp here: https://drive.google.com/file/d/1yrSDHS3hTl8S0ZiR2sMaes6rdZmG6YtZ/view?usp=sharing

And also thanks for the names, now I have titles to the .txtp and it's much better. I will take an another and more precise look to the instructions to generate it myself in the future.

I tried to manipulate the RTPC 1448701280 (its name is "BGM_BATTLE_DISTANCE" thanks to your file), but it affect all the .wem of the layer and not only one. According to the doc, the RTPC infos are in the comment in the .txtp, but the only things I see about it is "{0.0, 50.0}" which is, I suppose, a possible range of values, but nothing that can be indicate that a specific track can be muted. The only difference between the .wem files in a group is the ID after 'CAkMusicTrack", example: "CAkMusicTrack[850] **995521678**".

**Comment by bnnm** [comment]
Try this wip version, seems to generate those pause variations ok: [wwiser.zip](https://github.com/bnnm/wwiser/files/8405491/wwiser.zip)

In this case it's using extra "volume states" associated to certain CAkMusicTracks to change their volumes.

Btw, in .txtp you can silence a .wem by putting a `?` instead of commenting (`#`), no need to change group numbers this way (but not needed anymore with the above I guess)

**Comment by Auraylien** [comment]
Thanks for this version. It does not generate all .txtp versions but with the "ulStateGroupID", I can find which .wem track I have to mute or make volume low to get the variants (BGM_PAUSE_MENU: BGM_PUASE_MENU_IN for in menu music and also BGM_WAZA_TYPE: WAZA_POWER and BGM_WAZA_TYPE: WAZA_TECHNICAL that correspond to a variant I didn't know about).

And thanks for the tip with the `?` too!

**Comment by bnnm** [comment]
Try this again, wasn't lowering some volumes due to a bug: [wwiser.zip](https://github.com/bnnm/wwiser/files/8412399/wwiser.zip)

Other than that, which variations aren't generated?

Looks about the same to me:
`BGM-1733-event (2776459532=3902110436)(bgm_battle=3189526517)(1204638696=-) {s}` is
`PLAY_BGM_VS_NORA (BGM_VS_TYPE=VS_TYPE_NORA)(BGM_BATTLE=BATTLE_ON) {s}=-`
and
`BGM-1733-event (2776459532=3902110436)(bgm_battle=3189526517)(1204638696=-) {s} {edited}` is
`PLAY_BGM_VS_NORA (BGM_VS_TYPE=VS_TYPE_NORA)(BGM_BATTLE=BATTLE_ON) {s}=(BGM_PAUSE_MENU=BGM_PUASE_MENU_IN)(BGM_WAZA_TYPE=WAZA_POWER/WAZA_TECHNICAL)`

`BGM-2315-event (3832295740=4178474359) {d}` is
`PLAY_BGM_VS_TRAINER_01 (BGM_BATTLE_TRAINER=BATTLE_TRAINER_ON) {s}=-`
and
`BGM-2315-event (3832295740=4178474359) {d} {edited}` is
`PLAY_BGM_VS_TRAINER_01 (BGM_BATTLE_TRAINER=BATTLE_TRAINER_ON) {s}=(BGM_PAUSE_MENU=BGM_PUASE_MENU_IN)(BGM_WAZA_TYPE=WAZA_POWER/TECHNICAL)`

**Comment by Auraylien** [comment]
Thanks for this version, all versions are generated with this. I noticed that the songs "AREA0x" have multiple version inside the .txtp file, only the first is generated, but I think it's a thing I can get set with the options on wwiser. Here a link to a ZIP with an example of a "missing" variant: https://drive.google.com/file/d/114e_0PFxTwsxDH64fHoauO27K7LaJ-a6/view?usp=sharing

Thanks for you help with this issue, I'm sure this will help other people and help in the future with the next Pokemon games in end of the year that will probably use the same mecanic.

**Comment by bnnm** [comment]
To generate those `{r}` variations you need to manually set `Make multiple .txtp per base 'random' group`

Also see: https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#random-mark-r
