### ISSUE TITLE
wem_exists error [Elden Ring (Steam)]

### ISSUE THREAD

**Issue by modusc896d352** [bnnm/wwiser#17]
generator threw out some "PROCESS_ERROR" and demanded me report this here.
so here it is.
[wwiser.log](https://github.com/bnnm/wwiser/files/8607776/wwiser.log)

apologies for the lack of details.

**Comment by modusc896d352** [comment]
okay, as for how to "trigger" this error.
put the wem and bnk files in the same folder as wwiser.pyz. then "check" the option of "moving .wem to wem/ folder" for txtp stuff.
hope it helps.

**Comment by bnnm** [comment]
Should work with this: [wwiser.zip](https://github.com/bnnm/wwiser/files/8622364/wwiser.zip)

**Comment by modusc896d352** [comment]
OK, managed to test this one out and the whole error has been fixed. thanks.
