### ISSUE TITLE
Event name

### ISSUE THREAD

**Issue by alexeyglzkvgmail** [bnnm/wwiser#18]
Hello! How do I get the long event name from the short event name (Event ID), for example: "Play_Zomb_Egypt_Gargantuar_Mvmt_Attack_Throw"?

**Comment by bnnm** [comment]
If you mean how to reverse `Play_Zomb_Egypt_Gargantuar_Mvmt_Attack_Throw` back from `176208044` (Short ID), here is a guide: 
https://github.com/bnnm/wwiser-utils/blob/master/doc/NAMES.md

Event names in Wwise's editor (`Play_Zomb_Egypt_Gargantuar_Mvmt_Attack_Throw`) would become those numbers in the bank  (`176208044`).
