### ISSUE TITLE
BNK

### ISSUE THREAD

**Issue by alexeyglzkvgmail** [bnnm/wwiser#19]
Excuse me for coming to you, can you help me? Is it at all possible to edit BNK files? Or is it possible to present it in some format, so it can be read by Wwise? I just want to understand how this bnk file was created, so that I can create these files in Wwise myself.

**Comment by bnnm** [comment]
Sorry, this tool only shows the BNK's internal fields, and can't edit nor create files for Wwise.

Somebody else (not me) could make another program based on this tool that modifies those fields I guess, but given how complex Wwise is it would be pretty hard.
