### ISSUE TITLE
Can't TXTP Generator

### ISSUE THREAD

**Issue by tetsuki02** [bnnm/wwiser#2]
the reason is : WARNING! no .txtp were created (find+load banks with events?)
so when i check .bnk using HXD Software, not include HIRC. so how to fix to TXTP Generator ?

wwiser v20210119 (python 3.9.0)
parser: parsing C:/Users/Reynaldi/Desktop/New folder/export/ztool/TextAsset/new/61.bnk
parser: done
names: loading names
names: done
generator: start
generator: WARNING! no .txtp were created (find+load banks with events?)
generator: done (created 0)

![generate](https://user-images.githubusercontent.com/78646314/107117977-951a6580-68b0-11eb-9380-d0b72ca8e838.png)

**Comment by bnnm** [comment]
You do need to load .bnk with events (HIRC) together.

If you aren't sure which ones, try loading all .bnk in folder.

**Comment by tetsuki02** [comment]
Done sir, but still can't generate .txtp file

**Comment by tetsuki02** [comment]
and the problem is, it doesn't exist in it event (HIRC), so can't generate

**Comment by tetsuki02** [comment]
and the problem is, it doesn't exist in it event (HIRC), so can't generate
So sir, if i send .bnk without event (HIRC), can you fix it ?

**Comment by bnnm** [comment]
wwiser (and Wwise) must use .bnk with HIRC. If you don't find them that folder, it means main .bnk(s) are elsewhere, or inside another file. There is always one .bnk with HIRC.

If you simply want to hear .bnk with audio (DATA) you open them directly with vgmstream btw.

**Comment by tetsuki02** [comment]
But sir, if .bnk without event, so i can't know the name of the inside .bnk
?
Right ?

**Comment by tetsuki02** [comment]
Even though i know the name of all .wem in .bnk, but if it can't be
generated because there is no HIRC, then it won't be generated?
