### ISSUE TITLE
foobar2000 can't open *.txtp files

### ISSUE THREAD

**Issue by MarioPossamato** [bnnm/wwiser#21]
I have the vgmstream component installed, but it still says that the format is not supported.  Please let me know what to provide to resolve this issue :)

**Comment by bnnm** [comment]
Typically .wem aren't in the right folder or names are too long. Try following the tips here: https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#txtp-errors

Other than that you'd need to upload the generated .txtp, wem that the txtp uses, and the .bnks used to make that txtp.
