### ISSUE TITLE
Unsupported bank version

### ISSUE THREAD

**Issue by ClassicsWoTWorkshop** [bnnm/wwiser#23]
When attempting to unpack banks from World of Tanks, the program errors out, returning the following message:
> `parser: unsupported bank version 3539317264`

Not sure if this helps, but the game's documentation specifies a wwise version of "2019.2.3 or higher".

**Comment by bnnm** [comment]
Header is slightly encrypted, try this version and put xorpad.bin with the .bnk

[wwiser.zip](https://github.com/bnnm/wwiser/files/9096758/wwiser.zip)

**Comment by ClassicsWoTWorkshop** [comment]
New to the program -- how does one load xorpad.bin with the .bnk? I have placed it in the same folder as both the .bnk and the .pyz executable, but the parser throws the error `parser: encrypted bank version (needs xorpad.bin)` and fails to load the .bnk.

**Comment by bnnm** [comment]
Sorry, forgot to test the GUI. Try again now: [wwiser.zip](https://github.com/bnnm/wwiser/files/9097564/wwiser.zip)

If a .bnk is encrypted it'll try open xorpad.bin in the bnk's folder automatically.

**Comment by ClassicsWoTWorkshop** [comment]
Works! Thank you.
