### ISSUE TITLE
Question about converting txtp files on foobar2000 using latest version of vgmstream

### ISSUE THREAD

**Issue by Machow8** [bnnm/wwiser#25]
Hi,

I wanna know what i can be doing wrong, as foobar2000 isn't being able to recognise and play/convert majority of created txtp files (playback error shows "Unable to open item for playback (Unsupported format or corrupted file)");

Yes, i'm using the latest version of vgmstream plugin on foobar2000 (i downloaded it 2 days ago! lol ).

I placed bank, wem and txtp files in same root folder, as i understood after reading https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md txtp part of that link.

Do other non-txtp files need to be on other paths/folders/subfolders? Or what?

**Comment by bnnm** [comment]
I recommend reading this: https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#txtp-errors 

Also this: https://github.com/bnnm/wwiser-utils/blob/master/doc/RIPPING.md

**Comment by Machow8** [comment]
Hmn, so, my question is: the files should be located in the following paths, inside of txtp folder:

Lll txtp in root, while wem, bank, txt and xml be in wem folder, right?

Am i missing something?

**Comment by bnnm** [comment]
That is what the doc says, yes. Also check other pointers there like the file name limit.
.txtp are just text files so open them and see paths are correct and files exist.
