### ISSUE TITLE
Unable to view the properties inside of a Wwise Harmonizer effect.

### ISSUE THREAD

**Issue by Forsaken-Gaming** [bnnm/wwiser#26]
Hello! I am looking inside of Init.bnk that was made using v140. I can see the properties of other effects like Guitar Distortion, however the Harmonizer just displays this. Am I by chance missing something?
Thanks!
![Screenshot 2023-04-24 000819](https://user-images.githubusercontent.com/52881144/233898195-4142aa69-6d01-4fb2-92fe-ee618d110b81.png)
![Screenshot 2023-04-24 000834](https://user-images.githubusercontent.com/52881144/233898199-2c61e677-461d-4d30-91d7-32a2fd8b4d23.png)

Here are the relevant files: 
[init.zip](https://github.com/bnnm/wwiser/files/11306487/init.zip)

**Comment by bnnm** [comment]
I only added a few common plugins b/c they were time-consuming to include (separate from wwise itself needing to reverse engineer one by one) and didn't think most people would care. I'll add more if there is demand I guess.

**Comment by Forsaken-Gaming** [comment]
Oh yuck. I see. Thanks for the response!

**Comment by bnnm** [comment]
Did a quick implementation, seems ok but need to test earlier versions (<~v112): [wwiser.zip](https://github.com/bnnm/wwiser/files/11326807/wwiser.zip)

**Comment by Forsaken-Gaming** [comment]
Works perfectly on my end!
Thank you so much for going through the effort to do that!
