### ISSUE TITLE
AttenuationID using uid rather than sid

### ISSUE THREAD

**Issue by Forsaken-Gaming** [bnnm/wwiser#28]
While recreating soundbanks in Wwise, I had an issue where the AttenuationID would be a very tiny value. However, I found that if I modified the source code to make it register as an sid rather than an uid, it would work perfectly, allowing me to see the correct id it is assigned to. This happens with v140 banks and v134 banks. Not that big of an issue but I just wanted to let you know anyways!

**Comment by bnnm** [comment]
Sorry, could you elaborate a bit more? (samples would be helpful) uAttenuationID is set [here](https://github.com/bnnm/wwiser/blob/aae02c4f910cc24d186ea138380047e425add1e5/wwiser/parser/wparser.py#L841) as TID and I think would refer to some [attenuation's](https://github.com/bnnm/wwiser/blob/aae02c4f910cc24d186ea138380047e425add1e5/wwiser/parser/wparser.py#L2637) SID.

The distinction of tid/sid is just for wwiser to understand when it's a "target ID" (links to another) or regular "Short ID" (semi-unique object identifier). IIRC internally in Wwise it's just an uint32 implicitly used as ID or link depending on field.

**Comment by Forsaken-Gaming** [comment]
Absolutely!
With the attached files (v140) all of the AttenuationIds are super tiny numbers that don't link to anything. I looked at that exact part of the code myself and was thinking the same thing, honestly.
[Attenuation Example.zip](https://github.com/bnnm/wwiser/files/12231104/Attenuation.Example.zip)

**Comment by Forsaken-Gaming** [comment]
Ah, sorry for not making that clear. Works great! Thank you for fixing that! You're the best!
