### ISSUE TITLE
m3u file could not be generated...

### ISSUE THREAD

**Issue by RetingencyPlan** [bnnm/wwiser#3]
i think the title speaks for itself, but for brevity sake i'll try to explain everything.

so, there's this option in wwiser - the option to "Use shorter .txtp names and put full names in !tags.m3u" - that can be toggled in WWISER GUI version.
so i toggled it while generating entire txtp files.
and as the txtp files were generating, i got this...
```
txtp: saving 'Music-00360.txtp' (3379549342411585202)
generator: PROCESS ERROR! (report)

Traceback (most recent call last):
  File "C:\Users\###\Desktop\[python]wwiser\wwiser.pyz\wwiser\wgenerator.py", line 149, in generate
    self._write_tagsm3u()
  File "C:\Users\###\Desktop\[python]wwiser\wwiser.pyz\wwiser\wgenerator.py", line 438, in _write_tagsm3u
    with open(outname, 'w', newline="\r\n") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'txtp/!tags.m3u'
gui: generator stopped on error

```
i'm using the latest wwiser version available (v20210210), not using CLI version atm.
python 3.9.2 already installed into my Windows 10 PC.

**Comment by bnnm** [comment]
Should be fixed: https://github.com/bnnm/wwiser/releases/tag/v20210303

**Comment by RetingencyPlan** [comment]
thanks for the fix!
closing the issue now.
