### ISSUE TITLE
Unlikely count error

### ISSUE THREAD

**Issue by Zhincore** [bnnm/wwiser#31]
Hello,
This repo seems a little dead, but I'm desperate.
I'm trying to parse Cyberpunk 2077's `sfx_container.bnk` which has many entries in the HIRC section.
Wwiser seems to not like that, because it's replaces them with following in dumped banks:
```xml

		<fld ty="u32" na="NumReleasableHircItem" va="178879"/>
		<lst na="listLoadedItem" co="0"/>
		<error me="unlikely count 178879"/>
		<skip si="0xbc5627"/>
```

I am trying to parse bnks myself with help of wwiser's source code, but there's so much information...
Is there anything that could be done? I don't even know where the error comes from, it's nowhere in the master branch.

Thanks

**Comment by bnnm** [comment]
I've increased the limit, try this: [wwiser.zip](https://github.com/bnnm/wwiser/files/13074590/wwiser.zip) ([error](https://github.com/bnnm/wwiser/blob/71332dfbce6c8a88fc77ebcb6432058909a61450/wwiser/parser/wmodel.py#L461))

**Comment by Zhincore** [comment]
Works! Wonderful, thank you so much!

GitHub's search feature works in mysterious ways haha, it finds it when i put "unlikely count" in quotations, I didn't think of that.
