### ISSUE TITLE
Error while generating `!tags.m3u`

### ISSUE THREAD

**Issue by Razmoth** [bnnm/wwiser#32]
Seems to be from function name mismatch:

https://github.com/bnnm/wwiser/blob/master/wwiser/generator/wtags.py#L71
https://github.com/bnnm/wwiser/blob/master/wwiser/generator/wtags.py#L179

**Comment by bnnm** [comment]
Thanks, fixed: [wwiser.zip](https://github.com/bnnm/wwiser/files/13273099/wwiser.zip)
