### ISSUE TITLE
Inconsistent "sourceId" casing in XML export.

### ISSUE THREAD

**Issue by Zhincore** [bnnm/wwiser#37]
Hello,
I've noticed that [AkMediaMap has a field named `sourceId`](https://github.com/bnnm/wwiser/blob/13243b2e7c9f26e4ead63319b2fc8d1623f0e6e6/wwiser/parser/wparser.py#L2904C19-L2904C27) while [AkMediaInformation's field has name `sourceID`](https://github.com/bnnm/wwiser/blob/13243b2e7c9f26e4ead63319b2fc8d1623f0e6e6/wwiser/parser/wparser.py#L223) (with capital "D").
Is this inconsistency on purpose or just a mistake?

Thanks.

**Comment by bnnm** [comment]
Name inconsistencies are generally on purpose. Fields names were gotten from decompilations, so they should be accurate, meaning Audiokinetic simply isn't too consistent. (`rtpcID` is another common one) 

Some names may be slightly adapted though. Sometimes they may use stuff like `m_sourceID` while I remove the `m_` prefix (C++ class convention) for clarity. In other cases like `sourceId` (lowercase) name is only used in a temp variable and then converted to another nameless type (ex. an array/vector), but for wwiser I tried to keep names informative yet cross-referenciable vs decompilation, thus kept that particular case.

**Comment by Zhincore** [comment]
Alright, makes sense, thank you for the explanation!

Closing the issue since it's not an issue.
