### ISSUE TITLE
Mass Effect 2 Legendary Edition bnk files

### ISSUE THREAD

**Issue by Xehanort88** [bnnm/wwiser#39]
With ME3 tools I was finally able to get the elusive ME2 sound bank out, however wwiser doesn't seem able to make any use of them, or to generate the files even if put with the files as extracted (attached too).
[mus_endgm2_combat_3b_wav.zip](https://github.com/user-attachments/files/16636554/mus_endgm2_combat_3b_wav.zip)

[Default__WwiseBank.zip](https://github.com/user-attachments/files/16636494/Default__WwiseBank.zip)

Not sure if this is due to lack of overlapping transitions, which has been "coming" for like 3 years now, or due to something else. Happy to provide more files and screenshots.

**Comment by bnnm** [comment]
When you load banks there is a log that tells you what wwiser is doing and what doesn't like. It's saying that some of those bnk are `not a Wwise bank`.

If you open those banks with a hex editor, and remove all data before `BKHD` they should work. But consider checking why your bank extractor didn't get proper bnk as it may cause issues down the road or something.

**Comment by bnnm** [comment]
Missing busses means that you need to load `init.bnk`. It'll still work without it but you may get less accurate volumes in resulting music.

Transition objects is an unimplemented feature which probably isn't too noticeable.

Streams is just info that I could probably remove. It just means some txtp need `.wem`.

**Comment by Xehanort88** [comment]
Sadly, even with init.bnk (or in ME2LE case, SFXWwise_Init.Init.bnk) the issue is still there. 

generator: start
generator: processing nodes
generator: writting bank nodes (names: 0, unnamed: 0, filtered: 0)
generator: writting bank nodes (names: 0, unnamed: 10, filtered: 0)
txtp: saving 'Wwise_Cer_Sta_NonStreaming.Wwise_Cer_Sta_NonStreaming-0019-event.txtp' (-6737715692118173828)
txtp: saving 'Wwise_Cer_Sta_NonStreaming.Wwise_Cer_Sta_NonStreaming-0021-event.txtp' (5762007748206317209)
txtp: ignore 'Wwise_Cer_Sta_NonStreaming.Wwise_Cer_Sta_NonStreaming-0023-event' (repeat of 5762007748206317209)
txtp: ignore 'Wwise_Cer_Sta_NonStreaming.Wwise_Cer_Sta_NonStreaming-0027-event' (repeat of 5762007748206317209)
txtp: ignore 'Wwise_Cer_Sta_NonStreaming.Wwise_Cer_Sta_NonStreaming-0029-event' (repeat of 5762007748206317209)
generator: writting bank nodes (names: 0, unnamed: 2, filtered: 0)
txtp: saving 'Wwise_EndGame3_Music.Wwise_EndGame3_Music-0020-event [2737580204=_01].txtp' (7372946436794692387)
txtp: saving 'Wwise_EndGame3_Music.Wwise_EndGame3_Music-0020-event [2737580204=_02].txtp' (-2158212720655105307)
txtp: saving 'Wwise_EndGame3_Music.Wwise_EndGame3_Music-0020-event [2737580204=_03].txtp' (-2819533391898264983)
txtp: saving 'Wwise_EndGame3_Music.Wwise_EndGame3_Music-0020-event [2737580204=_04].txtp' (-689256628823962661)
generator: some .txtp (4) use streams
generator: some .txtp (2) use .bnk
- Wwise_Cer_Sta_NonStreaming.Wwise_Cer_Sta_NonStreaming.bnk
generator: done (created 6, 3 duplicates)

Even in this case, despite all files being in the bnk folder, they don't work.

Foobar error: Unable to open item for playback (Unsupported format or corrupted file):
"E:\EApp\Mass Effect Legendary Edition\Game\ME2\FINALE music\txtp\Wwise_EndGame3_Music.Wwise_EndGame3_Music-0020-event [2737580204=_04].txtp"

Attached a smaller, more manageable set of files for investigation including the generated txtp.
[Wwise_EndGame3_Music.zip](https://github.com/user-attachments/files/16639508/Wwise_EndGame3_Music.zip)

**Comment by bnnm** [comment]
Those txtp use streams (wem) like the log says.

wwiser can only work with Wwise numbers, so `mus_endgm3_cine_1_wav.wem` can't be used.

That is not a wwiser bug but just how Wwise works. You'd need to make sure those .wems are extracted and named using their original numbers.

**Comment by Xehanort88** [comment]
If the extraction method is the same how come some txtp are generated correctly?

**Comment by Xehanort88** [comment]
So, identifying the files via file ID does generate loops. but I still think there are overlapping transition issues as ther is a noticeable cut between loops, like in Wrath of the Righteous

**Comment by Xehanort88** [comment]
update: this is present for Pathfinder Wrath of the Righteous AND Warhammer Rogue trader as well.
