### ISSUE TITLE
Argument parsing error when using wwconfig.txt

### ISSUE THREAD

**Issue by lihaohong6** [bnnm/wwiser#40]
CLI argument: `python wwiser.pyz wwconfig.txt`

Content of `wwconfig.txt`:
```
-g -go txtp Test.bnk
```

The program exits with `error: unrecognized arguments: Test.bnk`.

Running the same commands in the CLI (`python wwiser.pyz -g -go txtp Test.bnk`) does not produce the above error. 

A quick fix is obtained by changing line 158 of `wcli.py` from `args = self._parser.parse_args(config)` to `args = self._parser.parse_args(config[1:])`. This fixes the error because `config` contains the name of the config file (`wwconfig.txt`), so `argparse` refuses to parse `Test.bnk` as it has already seen a positional argument at index 0, which is `wwconfig.txt`.

I'm not sure why the name of the config file gets added in `config` in the first place. Maybe there is a separate use case where this is helpful?

**Comment by bnnm** [comment]
Should work now.

**Comment by lihaohong6** [comment]
Thank you! Tested with the same input. It now works as intended.
