### ISSUE TITLE
Errors on some bnk's and vgmstream issues

### ISSUE THREAD

**Issue by Tamashh** [bnnm/wwiser#42]
Hello
I'm using the latest commit of wwiser and I'm trying to use it on Dead by Daylight audio but some bnk's give me errors for example `parser: parsing C:/FModel/Output/Exports/DeadByDaylight/Content/WwiseAudio/Cooked/AMB_01.bnk
parser: ERRORS! 19 found (report issue)`
I'm also having issues with vgmstream with some loose wem's for example `DeadByDaylight/Content/WwiseAudio/Cooked/Media/en/69/696359205.wem`
with this error: `WWISE: broken .wem (bad extract?) failed opening.`
You can use AssetRegistry.json as wwnames.txt.
wwiser log: [wwiserLOG.zip](https://github.com/user-attachments/files/16943743/wwiserLOG.zip)
Wwise folder from the game: [DBDAudio.rar](https://r2.tamashfiles.com/DBDAudio.rar)

**Comment by bnnm** [comment]
I've fixed the banks but don't think I can do much about those .wem. They do look broken to me, in a way that seems not possible to fix (wonky sizes and misaligned data). Only a few wem in `/en/` seem affected (other languages seem fine), so maybe the container file was somehow corrupted and needs to be redownloaded+extracted or something like that.

**Comment by Tamashh** [comment]
I'm pretty sure its some custom format that they are rolling out.
There was an update today and it seems like there are more loose wems that fail to convert.

**Comment by Tamashh** [comment]
After further testing I get 0 errors from both vgmstream and wwiser.
The files i provided were from 8.2.1 but after testing on 8.2.2 I get no errors.
So you were most likely right about the wem being broken.
