### ISSUE TITLE
Dead by Daylight 8.3.0 - .bnk and .txtp export errors

### ISSUE THREAD

**Issue by Electric-R4nger** [bnnm/wwiser#45]
Hello,
Tried exporting .txtp from the latest version of DBD using the latest version of wwiser. Worth noting I did not load any event name file since I could not dig it up out of DBD's pak files, so the .txtp would be event IDs only. (Although that's probably not relevant.)

Some .bnk's throw a `parser: ERRORS! (number) found (report issue)` in the log and trying to export .txtp from them throws a `TypeError: 'NodeObject' object is not iterable` exception, followed by a `ValueError: Error processing TXTP for node (number)` exception.
foobar with the vgmstream plugin plays the .bnk files just fine.

wwiser log: [wwiser.log](https://github.com/user-attachments/files/17299506/wwiser.log)
8.3.0 .bnk: [AMB_01.zip](https://github.com/user-attachments/files/17299564/AMB_01.zip)

**Comment by bnnm** [comment]
Should work with the latest nightly

https://github.com/bnnm/wwiser/releases/tag/latest-nightly
