### ISSUE TITLE
Effects parameters issue

### ISSUE THREAD

**Issue by Kopo6ka** [bnnm/wwiser#46]
Some effects, such as iZotope Multiband Distortion, Wwise Tremolo, McDSP ML 1, do not display parameters in wwiser. Because of this, it is impossible to restore them.
![Снимок экрана 2024-11-30 104736](https://github.com/user-attachments/assets/92763091-2b9d-4e64-851d-f1cb39fcc77f)

**Comment by bnnm** [comment]
Post samples, also see [this](https://github.com/bnnm/wwiser/issues/26).

**Comment by Kopo6ka** [comment]
> Post samples, also see [this](https://github.com/bnnm/wwiser/issues/26).

thanks

**Comment by bnnm** [comment]
No samples were posted so closing.
