### ISSUE TITLE
Outdated documentations on the -o argument

### ISSUE THREAD

**Issue by lihaohong6** [bnnm/wwiser#48]
An example CLI usage in the README is `wwiser -d txt init.bnk bgm.bnk -o banks.txt`, but running it would result in `unrecognized arguments -o`.  It seems that the `-o` argument was removed at some point and never added back. I checked `wcli.py`. Looks like `args.dump_name` in `wcli.py` is where the `-o` argument is supposed to be stored, but `-o` is not parsed by the argument parser since it is not in any of the `p.add_argument` statements.

**Comment by lihaohong6** [comment]
Adding something like `p.add_argument("-o", "--output", dest="dump_name")` in the `_parse_init` function should resolve this.

**Comment by bnnm** [comment]
The arg became `-dn` at some point during the development of initial version but forgot to update it, fixed.
