### ISSUE TITLE
Support version 89 banks?

### ISSUE THREAD

**Issue by nblockbuster** [bnnm/wwiser#7]
Right now the tool works with _some_ version 89 banks, but fails on ones that have music segments in them. In the viewer it gives me this error for music segments:
```
 error: {attrs[message]} {body}
(skipped {attrs[size]}) {body} 
```
inside of the AkMusicMarkerWwise object.
In the console for generating txtps I get these errors:
[wwiserlog.txt](https://github.com/bnnm/wwiser/files/7272831/wwiserlog.txt)
Here's one of the bank that it fails on:
[A3497A81.zip](https://github.com/bnnm/wwiser/files/7272835/A3497A81.zip)
and here's one of the files it exports txtps from correctly, this one only has dialogue:
[0A60D080.zip](https://github.com/bnnm/wwiser/files/7272838/0A60D080.zip)

Both of these bnks are from the PS4 version of Destiny 1, and both are version 89/0x59.
Thanks!

**Comment by bnnm** [comment]
Try this: [wwiser.zip](https://github.com/bnnm/wwiser/files/7273625/wwiser.zip)

If some bnk still fail just post all, otherwise it'll be a lot of back and forth.

**Comment by nblockbuster** [comment]
Thank you, It works like a charm! Just one last question: is there a way to get music txtps to generate with names? I noticed that in the A3497A81 bnk it says 'promise_music' at the end of the file and as the soundbank id in the viewer. If not completely, with event names and such is there atleast a way to get it to name the txtps something like `promise_music-0323-event [1246133352=1139621362](1433286457=none).txtp` instead of `A3497A81-0323-event [1246133352=1139621362](1433286457=none).txtp`? It gets the right name for sound effects and voice lines, so is there a way to modify it to work with music even if it doesn't have event names?

**Comment by nblockbuster** [comment]
Thank you, I really appreciate it!
