### ISSUE TITLE
Unsupported Bank Format

### ISSUE THREAD

**Issue by kloruklass** [bnnm/wwiser#9]
When I try to load a BNK it says:

parser: parsing E:/3_Kingdoms/BNK/battle_advice__core.bnk
parser: unsupported bank version 2147483777

**Comment by bnnm** [comment]
I can't do anything unless you 
you post

**Comment by kloruklass** [comment]
> I can't do anything unless you post the banks, preferably most of them, and the name of the game.

Hey, thanks for replying!

The game is "Total War Three Kingdoms."
These are the BNK files: [Three_Kingdoms_BNK](https://drive.google.com/file/d/18KNdM-5hurBRcsGa91OnHaxoeqONp_UN/view?usp=sharing)

**Comment by bnnm** [comment]
Should work now: [wwiser.zip](https://github.com/bnnm/wwiser/files/7566368/wwiser.zip)

In case those weren't all the banks, try loading other banks and check if the log doesn't report "errors" or "skips", as Total War games seem to use some funky custom Wwise version, that has some strange changes.

**Comment by kloruklass** [comment]
Everything seems to work fine, but when you try to use the TXTP Generator it gives your a sort of error and stops.

This is from **battle_individual_melee__core**
`nodes_named.sort() # usually gives better results with dupes
TypeError: '<' not supported between instances of 'NodeObject' and 'NodeObject'
gui: generator stopped on error`

**Comment by bnnm** [comment]
[wwiser.zip](https://github.com/bnnm/wwiser/files/7573420/wwiser.zip)

Fixed the second error but I can't trigger the first one, did some tweaks just in case. Which python version are you using? (shown near wwise version in the log). If it still happens, and you have extra files like SoundbanksInfo.xml post them too.

**Comment by kloruklass** [comment]
That's awesome!! Thank you very much!!

**Comment by bnnm** [comment]
I take it worked, so closing this.
